# User input

In [1]:
variable_of_interest = 'pr' # add list of available name variable
# the user should indicate the years of the period of interest
unit = 'mm_per_year'
period_of_interest = 'future'

# Import Packages and functions

In [2]:
import requests
import pandas as pd

import os
import os.path

from netCDF4 import Dataset

import xarray as xr

import numpy as np
import numpy.ma as ma

# to measure elapsed time
import time
from timeit import default_timer as timer

import multiprocessing as mp# to download several file in parrallel
from multiprocessing.pool import ThreadPool

# Functions

In [3]:
## Definition of tuples that will be useful to search which data are available or not
# make it tuples to make unchangeable
class copernicus_elements:
    # there is 58 models
    models =('access_cm2','awi_cm_1_1_mr','bcc_csm2_mr','cams_csm1_0','canesm5_canoe','cesm2_fv2','cesm2_waccm_fv2','cmcc_cm2_hr4','cmcc_esm2','cnrm_cm6_1_hr','e3sm_1_0','e3sm_1_1_eca','ec_earth3_aerchem','ec_earth3_veg','fgoals_f3_l','fio_esm_2_0','giss_e2_1_g','hadgem3_gc31_ll','iitm_esm','inm_cm5_0','ipsl_cm6a_lr','kiost_esm','miroc6','miroc_es2l','mpi_esm1_2_hr','mri_esm2_0','norcpm1','noresm2_mm','taiesm1','access_esm1_5','awi_esm_1_1_lr','bcc_esm1','canesm5','cesm2','cesm2_waccm','ciesm','cmcc_cm2_sr5','cnrm_cm6_1','cnrm_esm2_1','e3sm_1_1','ec_earth3','ec_earth3_cc','ec_earth3_veg_lr','fgoals_g3','gfdl_esm4','giss_e2_1_h','hadgem3_gc31_mm','inm_cm4_8','ipsl_cm5a2_inca','kace_1_0_g','mcm_ua_1_0','miroc_es2h','mpi_esm_1_2_ham','mpi_esm1_2_lr','nesm3','noresm2_lm','sam0_unicon','ukesm1_0_ll')
    experiments = ('ssp1_1_9','ssp1_2_6','ssp4_3_4','ssp5_3_4os','ssp2_4_5','ssp4_6_0','ssp3_7_0','ssp5_8_5')
    experiments_historical=('historical',)

In [4]:
if period_of_interest == 'past':
    scenarios=copernicus_elements.experiments_historical
    start_year = 1950
    stop_year = 2014
if period_of_interest == 'future':
    scenarios=copernicus_elements.experiments
    start_year = 2015
    stop_year = 2100

In [5]:
# function to extract the name of the file from its url
# the input is an url
def extract_name_file(url):
    index_before_name=url.rfind('/') # returns the highest index where the last character '/' was found, which is just before the name of the file    
    name = url[index_before_name+1:len(url)] # return the name of the file as a string, with the suffix '.nc'
    return name

# function 'produce_name_list' produce a list of files' name, with the suffix '.nc'
# 'produce_name_list' use the function 'extract_name_file' to have the name of a file from its url
# the input is a list of url, from which we want to extract the corresponding names of files
def produce_name_list(url_list):
    name_list=[] # create empty list
    for file in url_list:
        f_name = extract_name_file(file) # return the name of the file as a string, with the suffix '.nc'
        name_list.append(f_name) # add extracted name in the list
    return name_list # return the list of names in the url_list

In [6]:
# function produce_year produce:
#      year: a vector containing all the year in the period of interest
#      year_str: a array containing all the year in the period of interest in the string format
#      index: a array containing the index of the year and year_str
#### Parameters of the function
#      first_year: number in int format, of the first year of the period of interest
#      last_year: number in int format, of the last year of the period of interest
def produce_year(first_year,last_year):
    year = np.arange(first_year,(last_year+1),1) # create vector of years
    year_str = [0]*len(year) # create initiale empty vector to convert years in int
    index = np.arange(0,len(year)) # create vector of index for year
    i = 0 # initialize index
    for i in index: # convert all the date in string format
        year_str[i]=str(year[i])
    return (year, year_str, index)

In [7]:
# this functions aims to regroup all the scenarios, models, time_aggregation and variables in vectors
# the function use the function 'data_information'

def information_files_in_vectors(name_list):
    variables= []
    time_aggregations= []
    models= []
    scenarios= []
    for file_name in name_list:
        (variable, time_aggregation, model, scenario, year) = data_information(file_name) 
        # use function data_information to find information concerning the file_name
        if variable not in variables:
            variables.append(variable)
        if time_aggregation not in time_aggregations:
            time_aggregations.append(time_aggregation)
        if model not in models:
            models.append(model)
        if scenario not in scenarios:
            scenarios.append(scenario)
    return variables, time_aggregations,models,scenarios

In [8]:
# this functions aims to return the closest latitudes and longitudes to the projects, and the respectives index 
#  in the lat and lon vectors of the file
def _lat_lon(path,lat_projects,lon_projects):
    ds =  xr.open_dataset(path) 
    # ds.indexes['time'] gives back CFTimeIndex format, with hours. The strftime('%d-%m-%Y') permits to have time 
    # as an index, with format '%d-%m-%Y'. The .values permits to have an array
    lat  = ds.lat.values
    lon  = ds.lon.values
    ds.close() # to spare memory
    # preallocate space for the future vectors
    index_closest_lat = []
    index_closest_lon = []
    closest_value_lat = []
    closest_value_lon = []
    for j in np.arange(0,len(lat_projects)):
        (A,B)=closest_lat_lon_to_proj(lat_projects[j],lat)
        index_closest_lat.append(A[0])
        closest_value_lat.append(B[0])
        (C,D)=closest_lat_lon_to_proj(lon_projects[j],lon)
        index_closest_lon.append(C[0])
        closest_value_lon.append(D[0])
    return index_closest_lat,index_closest_lon,closest_value_lat,closest_value_lon

In [9]:
# this function aims to select the closest point to the geographical point of the project
# the function takes as input 
#     location_project, which is a numpy.float64
#     vector, which is a numpy.ndarray
# the function returns
#     closest_value[0], a numpy.float64

def closest_lat_lon_to_proj(location_project,vector):
    # the function any() returns a boolean value. Here, the function test if there are elements in the array 
    # containing the difference between the vector and the location_project, equal to the minimum of the absolute 
    # value of the difference between the vector and the location_project
    if any(np.where((vector - location_project) == min(abs(vector - location_project)))[0]):
        # the function any() returned True
        # there is an element in the vector that is equal to the minimum of the absolute value of the difference 
        # between the vector and the location_project
        
        # the function np.where() returns the index for which (vector - location_project) == min(abs(vector - location_project))
        index_closest = np.where((vector - location_project) == min(abs(vector - location_project)))[0]
        closest_value = vector[index_closest]
    else:
        # the function any() returned False
        # there is NO element in the vector that is equal to the minimum of the absolute value of the difference 
        # between the vector and the location_project
        
        # the function np.where() returns the index for which (vector - location_project) == -min(abs(vector - location_project))
        index_closest = np.where((vector - location_project) == -min(abs(vector - location_project)))[0]
        closest_value = vector[index_closest]
    return index_closest, closest_value 
    # the function returns
    #     first, the value of the index of the element of vector, that is the closest to location_project    
    #     second, the array containing the element of vector, that is the closest to location_project

In [10]:
## those three function are used to have the information concerning a file
## information are in the name of the file, so the name of the file is used to find its related information
## information mean variable, time_aggregation, model, scenario, year of the file

### this function permit to extract the word before the first character '_' in the input 'name'
### the input name is in format str
### returning the new_name, without the word found, will permit to re-use the function to find all 
#     the information concerning the studied file
def name_next_boundary(name):
    index_before_name=name.find('_') # returns the lowest index where the character '_' was found
    word = name[0:index_before_name] # first word in the string 'name', before the first character '_'
    new_name = name.replace(word+'_','') # delete the word found from the string 'name'
    return word, new_name # return, in string format, the word found (which is an information of the studied file), 
                    # and the string 'new_name', which is 'name' without the word found

# this function permit to extract the year of the studied file
# the year is always writen at the end of the name's file
# the input name is in format str
def find_year(name):
    index_before_name=name.rfind('_') # returns the highest index where the character '_' was found
    # the last character '_' is just before the year in the string 'name'
    # determine if the string 'name' ends with '.nc'
    if name.endswith('.nc'):
        # 'name' ends with '.nc'
        name_end = 3 # the three last character of the string name will be removed to find the year of the studied file
    else:
        # 'name' does not end with '.nc'
        name_end = 0 # no character will be removed at the end of 'name' to find the year of the studied file
    year = name[index_before_name+1:len(name)-name_end] # the year is extracted from the name of the file studied
    # based on the index_before_name (highest index where the character '_' was found) and the suffix of 'name'
    return year # the year in string format is returned

# This function use the functions 'name_next_boundary' and 'find_year' to extract the information of the file studied
# the input name is in format str, the name of the file from which we want information
def data_information(name):
    #### use of the function 'name_next_boundary': each time it is used, 
    # returns an information, and the name of the studied file without this information
    (variable, shorten_name) = name_next_boundary(name)
    (time_aggregation, shorten_name) = name_next_boundary(shorten_name)
    (model, shorten_name) = name_next_boundary(shorten_name)
    (scenario, shorten_name) = name_next_boundary(shorten_name)
    #### use the function 'find_year' to extract the information 'year' from the string 'shorten_name'
    year = find_year(shorten_name)
    # the function returns all the information of the studied file
    return variable, time_aggregation, model, scenario, year

In [11]:
# this function aims to create the empty dataframe that will be filled
def create_empty_dataframe(name_project,scenarios,models,time,closest_value_lat,closest_value_lon,name_variable,unit):
    df = pd.DataFrame()
    for i in np.arange(0,len(name_project)):
        print(closest_value_lat[i])
        for j in np.arange(0,len(closest_value_lat[i])):
            midx = pd.MultiIndex.from_product([(name_project[i],),(scenarios,), (models,), time, list((closest_value_lat[i][j],)),list((closest_value_lon[i][j],))],names=['Name project','Experiment', 'Model', 'Date', 'Latitude','Longitude'])
            cols = pd.MultiIndex.from_product([(name_variable+' '+unit,)])
            Variable_dataframe = pd.DataFrame(data = [], 
                                        index = midx,
                                        columns = cols)
            df = pd.concat([df,Variable_dataframe])
    return df

In [12]:
# this function is used in 'create_dataframe'. The function aims to return the path of the file of interest
# The function looks into a list of name which name in the list has every input 
# The inputs are:
#    out_path: a general file path where the files are registered, 
#    name_file_list: a list of files' names
#    variable: the name of the variable of interest
#    model: the model of interest (example: ACCESS-CM2)
#    scenario: the scenario of interest (example:ssp245)
#    year: the year of interest
#    ensemble: the ensemble of interest (example: r1i1p1f1_gn)
# the output is:
#    the path of the file corresponding to all the parameters indicated in input

def find_path_file(out_path,name_file_list,variable,temporal_resolution,model,scenario,year,ensemble):
    # look into the list of names if find a name with every parameter indicated in inputs
    name_found = [name for name in name_file_list if scenario in name and model in name and year in name and ensemble in name and temporal_resolution in name]
    try:
        print('The name of the file is ' + name_found[0])
    except:
        if name_found == []:
            print('the file was not found; scenario '+scenario+' model '+model +' ensemble '+ensemble)
            # no name with all the parameters indicated as inputs was found
            return name_found # return an empty element instead of a path, the function does not run the following lines
    # the name was found, so prepare the path of the file of interest
    path = os.path.join(out_path,name_found[0])
    return path # return the path of the file of interest

In [36]:
# the register_data_in_dataframe function aims to test if data with the specific parameters exist in the folder of concern
# As inputs :
#      the list of urls of the files of interest. The name of the file will be extracted from them
#      temporal_resolution: the temporal resolution of the climate variable in question in string format
#      year_str: a vector containing the year of the period of interest in a string format
#      scenarios: a list of the scenorios of interest in string format
#      models: a list of the models of interest in string format
#      out_path: the out_path in a string format
#      name_variable: the name of the variable of interest (example: 'pr' for precipitation)
#      name_project: the list of names of the project of interest
#      index_closest_lat: array containing an index for each project, 
#                           corresponding to the index of the value in latitude vector which is the closest to 
#                           the project latitude
#      index_closest_lat: array containing an index for each project, 
#                           corresponding to the index of the value in longitude vector which is the closest to 
#                           the project longitude
#      closest_value_lat: array containing a value for each project, corresponding to the value in the 
#                           latitude vector which is the closest to the project's latitude
#      closest_value_lon: array containing a value for each project, corresponding to the value in the 
#                           longitude vector which is the closest to the project's longitude
#      df : empty dataframe to fill

# Outputs are:
#      df: the filled dataframe with the values of interest
#      path_file_not_found: the list of files that were not found with the parameters asked
#      ds_did_not_open: the list of files that could not be read

def register_data_in_dataframe(name_list,temporal_resolution,year_str,scenarios,models,out_path, name_variable, name_project,lat_projects,lon_projects):#,index_closest_lat,index_closest_lon,closest_value_lat,closest_value_lon,df):    
    path_file_not_found = [] # create empty list to register names of files that were not found with the corresponding parameters
    ds_did_not_open = [] # create empty list to register names of files that couldn't be opened
    df_final = pd.DataFrame() # create an empty datafram to contain all the informations
    if name_variable =='pr':
        conversion_factor = 86400
        conversion_addition = 0
    
    for year in year_str:
        for SSP in scenarios:
            for model_simulation in models:
                # for each year, each scenarios and each models, test if there is a corresponding file existing
                # with function 'find_path_file'
                climate_variable_path = find_path_file(out_path,name_list,name_variable,temporal_resolution,model_simulation,SSP,year,'r1i1p1f1_gn')
                if climate_variable_path!= []:
                # a file with the corresponding parameters were found
                    print('Look for closest lat and lon')
                    index_closest_lat = []
                    while index_closest_lat == []: # once the information where extracted, no need to continue looking
                        try: # test to use function '_lat_lon' with this path
                            (index_closest_lat,index_closest_lon,closest_value_lat,closest_value_lon)=_lat_lon(climate_variable_path,lat_projects,lon_projects)
                            print(index_closest_lat)
                            print(index_closest_lon)
                            # this function '_lat_lon' use xr.open_dataset(path). If there is a problem with this opening process
                            # (because the path given has a problem for example), the function can continue to test with the next 
                            # file to extract the information of interest (the index and value of the closest latitude and longitude)
                        except:
                            continue # the informations where not extracted. Continue the for loop

                    # select some informatuons around the point of interest
                    index_closest_lat = pd.Series(index_closest_lat)
                    index_closest_lon = pd.Series(index_closest_lon)
                    index_lat_of_interest = [index_closest_lat -1, index_closest_lat, index_closest_lat+1]
                    index_lon_of_interest = [index_closest_lon -1, index_closest_lon, index_closest_lon+1]
                    index_lat_of_interest = pd.DataFrame(index_lat_of_interest)
                    index_lon_of_interest = pd.DataFrame(index_lon_of_interest)
                    
                    try: # to register information from the dataset ds in the dataframe df
                        ds =  xr.open_dataset(climate_variable_path) # open the file corresponding to the parameters
                        print('The file opened successfully')
                    except: # the dataset ds can not be read
                        # add information of the dataset that can't be read in the empty list ds_did_not_open
                        ds_did_not_open.append(climate_variable_path)
                        print(climate_variable_path + ' did not open with ds')
                        ds.close() # the opened dataset is closed to spare memory
                        continue # try with next model   
                    
                    # convert latitudes and longitudes if not in degrees
                    print('convert lat and lon')
                    lat = ds.lat.values
                    lon = ds.lon.values
                    if max(ds.lat.values)>90:
                        for i in np.arange(0,len(lat)):
                            if lat[i] >90:
                                lat[i] = lat[i] - 180
                    if max(ds.lon.values)>180:
                        for j in np.arange(0,len(lon)):
                            if lon[i] >180:
                                lon[i] = lon[i] - 360

                    lat_of_interest=[lat[index_lat_of_interest[0]]]#,lat[index_lat_of_interest[1]],lat[index_lat_of_interest[2]],lat[index_lat_of_interest[3]]] 
                    lon_of_interest=[lon[index_lon_of_interest[0]]]#,lon[index_lon_of_interest[1]],lon[index_lon_of_interest[2]],lon[index_lon_of_interest[3]]]
                    print(lat_of_interest)
                    print(lon_of_interest)
                    time = ds.indexes['time'].strftime('%d-%m-%Y').values # register the time in the file

                    df=create_empty_dataframe(name_project,SSP,model_simulation,time,lat_of_interest,lon_of_interest,name_variable,unit)                        
                    print('Empty df')
                    
                    for p in np.arange(0,len(name_project)):
                        for k in np.arange(0,len(lat_of_interest)-1):
                            print('For the year '+year+' and project '+name_project[p]+', test with scenario '+SSP+', with model '+model_simulation)
                            # for each year, scenarios, models and each project, the values of the opened dataset ds
                            # are registered in the empty dataframe df, to a specific place corresponding to the parameters of the loop
                            df.loc[(name_project[p],SSP,model_simulation,time,lat_of_interest[p][k],lon_of_interest[p][k]),(name_variable+' '+unit,)] = ds.variables[name_variable].isel(lat=index_lat_of_interest[p][k],lon=index_lon_of_interest[p][k]).values*conversion_factor+conversion_addition
                    ds.close() # the opened dataset is closed to spare memory
                    df_final = pd.concat([df_final,df])
                    print('df')
                    print(df)
                    print('df_final')
                    print(df_final)

                else:
                    # NO file with the corresponding parameters were found
                    # add information of the missing file in the empty list path_file_not_found
                    path_file_not_found.append(name_variable+'_'+temporal_resolution+'_'+model_simulation+'_'+SSP+'_'+year+'_'+'r1i1p1f1_gn')
                    continue # try another file
    return df_final,path_file_not_found,ds_did_not_open

# the function df_to_csv aims to return the filled dataframe in a csv format
# Inputs are:
#       df: the dataframe that should be register in a csv file
#      path_for_csv: this is the path where the csv file should be registered, in a string format
#      title_file: this is the name of the csv file to be created in a string format
#                  CAREFUL --> title_file MUST have the extension of the file in the string (.csv for example)
# Output is:
#      in the case where the dataframe is not empty, the ouput is the full path to the created csv file
#      in the case where the dataframe is empty, the output is an empty list
def df_to_csv(df,path_for_csv,title_file):
    # test if dataframe is empty, if values exist for this period
    if not df.empty: 
        # if dataframe is not empty, value were registered, the first part is run : 
        # a path to register the csv file is created, .....
        if not os.path.isdir(path_for_csv):
            # the path to the file does not exist
            os.makedirs(path_for_csv) # to ensure creation of the folder
            # creation of the path for the csv file, in a string format
        full_name = os.path.join(path_for_csv,title_file)
        # ..... and the dataframe is registered in a csv file
        df.to_csv(full_name) # register dataframe in csv file
        print('Path for csv file is: ' + full_name)
        return full_name # return the full path that leads to the created csv file
    else: # if the dataframe is empty, no value were found, there is no value to register or to return
        print('The dataframe is empty')
        return []

# Projects information


In [14]:
# Project information

name_project_data = np.array(['WTP_Mutua_EIB', 'Gorongosa_EIB', 'Chimoio_WTP_EIB', 'Pemba_EIB'])
name_project = pd.Series(name_project_data)

lon_projects_data = np.array([34.5927839939706, 34.07824286310398 , 33.47333313659342, 40.52545156033736])
lon_projects = pd.Series(lon_projects_data)

lat_projects_data = np.array([-19.495079648575242, -18.68063728746643, -19.125095255188334,-12.973942656747809])
lat_projects = pd.Series(lat_projects_data)

# Define Paths

In [15]:
out_path=r'\\COWI.net\projects\A245000\A248363\CRVA\Datasets\NEX-GDDP-CMIP6-AllMoz'

# Complete list of url with files to download

In [16]:
# register information from csv file
#all_urls = pd.read_csv(r'C:\Users\CLMRX\OneDrive - COWI\Documents\GitHub\CRVA_tool\outputs\NEX-GDDP-CMIP6\gddp-cmip6-thredds-fileserver.csv')
csv_path = os.path.join(out_path,'gddp-cmip6-thredds-fileserver.csv')
all_urls = pd.read_csv(csv_path)

In [17]:
### make all elements of the csv into a readable list

temp_list = all_urls[[' fileUrl']].T# transpose csv
temp_list=temp_list.values.tolist()
temp_list=temp_list[0]
url_list=[s.replace(' ', '') for s in temp_list]

In [18]:
## download only precipitation data
# select only precipitation files, between 2040 and 2080
url_list_climate_var = [url for url in url_list if variable_of_interest+'_' in url and int(url[len(url)-7:len(url)-3])>=start_year and int(url[len(url)-7:len(url)-3])<=stop_year and 'r1i1p1f1_gn' in url]

In [19]:
len(url_list_climate_var)

5069

In [20]:
name_list_climate_var = produce_name_list(url_list_climate_var)

In [21]:
name_list_climate_var[0]

'pr_day_ACCESS-CM2_ssp245_r1i1p1f1_gn_2015.nc'

# Produce csv files with data to use

In [22]:
(year, year_str, index_year) = produce_year(start_year,stop_year)
time = pd.date_range('01-01-'+str(start_year),'31-12-'+str(stop_year), freq='D').strftime('%d-%m-%Y').values # use to create dataframe

In [23]:
# variables, time_aggregations,models,scenarios in the name_list_precipitation
(variables, time_aggregations,models,scenarios)=information_files_in_vectors(name_list_climate_var)

In [24]:
scenarios

['ssp245', 'ssp585', 'ssp126', 'ssp370']

In [25]:
project = 0

In [37]:
#df_climate_var=register_data_in_dataframe(name_list_climate_var,time_aggregations[0],year_str,scenarios,models,out_path, variable_of_interest, name_project,lon_projects,lat_projects,index_closest_lat,index_closest_lon,closest_value_lat,closest_value_lon,df_climate_var)
start_t = timer()
#(df_climate_var,path_file_not_found,ds_did_not_open)
(df_climate_var,path_file_not_found,ds_did_not_open)=register_data_in_dataframe(name_list_climate_var,time_aggregations[0],year_str,['ssp245'],[models[0]],out_path, variable_of_interest, [name_project[project]],[lat_projects[project]],[lon_projects[project]])#,[index_closest_lat[0]],[index_closest_lon[0]],[closest_value_lat[0]],[closest_value_lon[0]],df_climate_var)
#(df_climate_var,path_file_not_found,ds_did_not_open)=register_data_in_dataframe(name_list_climate_var,time_aggregations[0],year_str,[scenarios[0]],[models[0]],out_path, variable_of_interest, [name_project[0]])#,[index_closest_lat[0]],[index_closest_lon[0]],[closest_value_lat[0]],[closest_value_lon[0]],df_climate_var)
end_t = timer()
print('It took '+str(round(end_t - start_t,2))+' seconds to register the data of interest in dataframe')
print('It took '+str(round((end_t - start_t)/3600,2))+' hours to register the data of interest in dataframe')

The name of the file is pr_day_ACCESS-CM2_ssp245_r1i1p1f1_gn_2015.nc
Look for closest lat and lon
[42]
[18]
The file opened successfully
convert lat and lon
[array([-19.625, -19.375, -19.125])]
[array([34.375, 34.625, 34.875])]
[-19.625 -19.375 -19.125]
Empty df
df
                                                                  pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2015 -19.625  34.375               NaN
                                    02-01-2015 -19.625  34.375               NaN
                                    03-01-2015 -19.625  34.375               NaN
                                    04-01-2015 -19.625  34.375               NaN
                                    05-01-2015 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2015 -19.125  34.875               NaN
     

[42]
[18]
The file opened successfully
convert lat and lon
[array([-19.625, -19.375, -19.125])]
[array([34.375, 34.625, 34.875])]
[-19.625 -19.375 -19.125]
Empty df
df
                                                                  pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2019 -19.625  34.375               NaN
                                    02-01-2019 -19.625  34.375               NaN
                                    03-01-2019 -19.625  34.375               NaN
                                    04-01-2019 -19.625  34.375               NaN
                                    05-01-2019 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2019 -19.125  34.875               NaN
                                    28-12-2019 -19.125  34.875               NaN
                      

[42]
[18]
The file opened successfully
convert lat and lon
[array([-19.625, -19.375, -19.125])]
[array([34.375, 34.625, 34.875])]
[-19.625 -19.375 -19.125]
Empty df
df
                                                                  pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2023 -19.625  34.375               NaN
                                    02-01-2023 -19.625  34.375               NaN
                                    03-01-2023 -19.625  34.375               NaN
                                    04-01-2023 -19.625  34.375               NaN
                                    05-01-2023 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2023 -19.125  34.875               NaN
                                    28-12-2023 -19.125  34.875               NaN
                      

[42]
[18]
The file opened successfully
convert lat and lon
[array([-19.625, -19.375, -19.125])]
[array([34.375, 34.625, 34.875])]
[-19.625 -19.375 -19.125]
Empty df
df
                                                                  pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2027 -19.625  34.375               NaN
                                    02-01-2027 -19.625  34.375               NaN
                                    03-01-2027 -19.625  34.375               NaN
                                    04-01-2027 -19.625  34.375               NaN
                                    05-01-2027 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2027 -19.125  34.875               NaN
                                    28-12-2027 -19.125  34.875               NaN
                      

[42]
[18]
The file opened successfully
convert lat and lon
[array([-19.625, -19.375, -19.125])]
[array([34.375, 34.625, 34.875])]
[-19.625 -19.375 -19.125]
Empty df
df
                                                                  pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2031 -19.625  34.375               NaN
                                    02-01-2031 -19.625  34.375               NaN
                                    03-01-2031 -19.625  34.375               NaN
                                    04-01-2031 -19.625  34.375               NaN
                                    05-01-2031 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2031 -19.125  34.875               NaN
                                    28-12-2031 -19.125  34.875               NaN
                      

[42]
[18]
The file opened successfully
convert lat and lon
[array([-19.625, -19.375, -19.125])]
[array([34.375, 34.625, 34.875])]
[-19.625 -19.375 -19.125]
Empty df
df
                                                                  pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2035 -19.625  34.375               NaN
                                    02-01-2035 -19.625  34.375               NaN
                                    03-01-2035 -19.625  34.375               NaN
                                    04-01-2035 -19.625  34.375               NaN
                                    05-01-2035 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2035 -19.125  34.875               NaN
                                    28-12-2035 -19.125  34.875               NaN
                      

[42]
[18]
The file opened successfully
convert lat and lon
[array([-19.625, -19.375, -19.125])]
[array([34.375, 34.625, 34.875])]
[-19.625 -19.375 -19.125]
Empty df
df
                                                                  pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2039 -19.625  34.375               NaN
                                    02-01-2039 -19.625  34.375               NaN
                                    03-01-2039 -19.625  34.375               NaN
                                    04-01-2039 -19.625  34.375               NaN
                                    05-01-2039 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2039 -19.125  34.875               NaN
                                    28-12-2039 -19.125  34.875               NaN
                      

[42]
[18]
The file opened successfully
convert lat and lon
[array([-19.625, -19.375, -19.125])]
[array([34.375, 34.625, 34.875])]
[-19.625 -19.375 -19.125]
Empty df
df
                                                                  pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2043 -19.625  34.375               NaN
                                    02-01-2043 -19.625  34.375               NaN
                                    03-01-2043 -19.625  34.375               NaN
                                    04-01-2043 -19.625  34.375               NaN
                                    05-01-2043 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2043 -19.125  34.875               NaN
                                    28-12-2043 -19.125  34.875               NaN
                      

[42]
[18]
The file opened successfully
convert lat and lon
[array([-19.625, -19.375, -19.125])]
[array([34.375, 34.625, 34.875])]
[-19.625 -19.375 -19.125]
Empty df
df
                                                                  pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2047 -19.625  34.375               NaN
                                    02-01-2047 -19.625  34.375               NaN
                                    03-01-2047 -19.625  34.375               NaN
                                    04-01-2047 -19.625  34.375               NaN
                                    05-01-2047 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2047 -19.125  34.875               NaN
                                    28-12-2047 -19.125  34.875               NaN
                      

[42]
[18]
The file opened successfully
convert lat and lon
[array([-19.625, -19.375, -19.125])]
[array([34.375, 34.625, 34.875])]
[-19.625 -19.375 -19.125]
Empty df
df
                                                                  pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2051 -19.625  34.375               NaN
                                    02-01-2051 -19.625  34.375               NaN
                                    03-01-2051 -19.625  34.375               NaN
                                    04-01-2051 -19.625  34.375               NaN
                                    05-01-2051 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2051 -19.125  34.875               NaN
                                    28-12-2051 -19.125  34.875               NaN
                      

[42]
[18]
The file opened successfully
convert lat and lon
[array([-19.625, -19.375, -19.125])]
[array([34.375, 34.625, 34.875])]
[-19.625 -19.375 -19.125]
Empty df
df
                                                                  pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2055 -19.625  34.375               NaN
                                    02-01-2055 -19.625  34.375               NaN
                                    03-01-2055 -19.625  34.375               NaN
                                    04-01-2055 -19.625  34.375               NaN
                                    05-01-2055 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2055 -19.125  34.875               NaN
                                    28-12-2055 -19.125  34.875               NaN
                      

[42]
[18]
The file opened successfully
convert lat and lon
[array([-19.625, -19.375, -19.125])]
[array([34.375, 34.625, 34.875])]
[-19.625 -19.375 -19.125]
Empty df
df
                                                                  pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2059 -19.625  34.375               NaN
                                    02-01-2059 -19.625  34.375               NaN
                                    03-01-2059 -19.625  34.375               NaN
                                    04-01-2059 -19.625  34.375               NaN
                                    05-01-2059 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2059 -19.125  34.875               NaN
                                    28-12-2059 -19.125  34.875               NaN
                      

[42]
[18]
The file opened successfully
convert lat and lon
[array([-19.625, -19.375, -19.125])]
[array([34.375, 34.625, 34.875])]
[-19.625 -19.375 -19.125]
Empty df
df
                                                                  pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2063 -19.625  34.375               NaN
                                    02-01-2063 -19.625  34.375               NaN
                                    03-01-2063 -19.625  34.375               NaN
                                    04-01-2063 -19.625  34.375               NaN
                                    05-01-2063 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2063 -19.125  34.875               NaN
                                    28-12-2063 -19.125  34.875               NaN
                      

[42]
[18]
The file opened successfully
convert lat and lon
[array([-19.625, -19.375, -19.125])]
[array([34.375, 34.625, 34.875])]
[-19.625 -19.375 -19.125]
Empty df
df
                                                                  pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2067 -19.625  34.375               NaN
                                    02-01-2067 -19.625  34.375               NaN
                                    03-01-2067 -19.625  34.375               NaN
                                    04-01-2067 -19.625  34.375               NaN
                                    05-01-2067 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2067 -19.125  34.875               NaN
                                    28-12-2067 -19.125  34.875               NaN
                      

[42]
[18]
The file opened successfully
convert lat and lon
[array([-19.625, -19.375, -19.125])]
[array([34.375, 34.625, 34.875])]
[-19.625 -19.375 -19.125]
Empty df
df
                                                                  pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2071 -19.625  34.375               NaN
                                    02-01-2071 -19.625  34.375               NaN
                                    03-01-2071 -19.625  34.375               NaN
                                    04-01-2071 -19.625  34.375               NaN
                                    05-01-2071 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2071 -19.125  34.875               NaN
                                    28-12-2071 -19.125  34.875               NaN
                      

[42]
[18]
The file opened successfully
convert lat and lon
[array([-19.625, -19.375, -19.125])]
[array([34.375, 34.625, 34.875])]
[-19.625 -19.375 -19.125]
Empty df
df
                                                                  pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2075 -19.625  34.375               NaN
                                    02-01-2075 -19.625  34.375               NaN
                                    03-01-2075 -19.625  34.375               NaN
                                    04-01-2075 -19.625  34.375               NaN
                                    05-01-2075 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2075 -19.125  34.875               NaN
                                    28-12-2075 -19.125  34.875               NaN
                      

[42]
[18]
The file opened successfully
convert lat and lon
[array([-19.625, -19.375, -19.125])]
[array([34.375, 34.625, 34.875])]
[-19.625 -19.375 -19.125]
Empty df
df
                                                                  pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2079 -19.625  34.375               NaN
                                    02-01-2079 -19.625  34.375               NaN
                                    03-01-2079 -19.625  34.375               NaN
                                    04-01-2079 -19.625  34.375               NaN
                                    05-01-2079 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2079 -19.125  34.875               NaN
                                    28-12-2079 -19.125  34.875               NaN
                      

[42]
[18]
The file opened successfully
convert lat and lon
[array([-19.625, -19.375, -19.125])]
[array([34.375, 34.625, 34.875])]
[-19.625 -19.375 -19.125]
Empty df
df
                                                                  pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2083 -19.625  34.375               NaN
                                    02-01-2083 -19.625  34.375               NaN
                                    03-01-2083 -19.625  34.375               NaN
                                    04-01-2083 -19.625  34.375               NaN
                                    05-01-2083 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2083 -19.125  34.875               NaN
                                    28-12-2083 -19.125  34.875               NaN
                      

[42]
[18]
The file opened successfully
convert lat and lon
[array([-19.625, -19.375, -19.125])]
[array([34.375, 34.625, 34.875])]
[-19.625 -19.375 -19.125]
Empty df
df
                                                                  pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2087 -19.625  34.375               NaN
                                    02-01-2087 -19.625  34.375               NaN
                                    03-01-2087 -19.625  34.375               NaN
                                    04-01-2087 -19.625  34.375               NaN
                                    05-01-2087 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2087 -19.125  34.875               NaN
                                    28-12-2087 -19.125  34.875               NaN
                      

[42]
[18]
The file opened successfully
convert lat and lon
[array([-19.625, -19.375, -19.125])]
[array([34.375, 34.625, 34.875])]
[-19.625 -19.375 -19.125]
Empty df
df
                                                                  pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2091 -19.625  34.375               NaN
                                    02-01-2091 -19.625  34.375               NaN
                                    03-01-2091 -19.625  34.375               NaN
                                    04-01-2091 -19.625  34.375               NaN
                                    05-01-2091 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2091 -19.125  34.875               NaN
                                    28-12-2091 -19.125  34.875               NaN
                      

[42]
[18]
The file opened successfully
convert lat and lon
[array([-19.625, -19.375, -19.125])]
[array([34.375, 34.625, 34.875])]
[-19.625 -19.375 -19.125]
Empty df
df
                                                                  pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2095 -19.625  34.375               NaN
                                    02-01-2095 -19.625  34.375               NaN
                                    03-01-2095 -19.625  34.375               NaN
                                    04-01-2095 -19.625  34.375               NaN
                                    05-01-2095 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2095 -19.125  34.875               NaN
                                    28-12-2095 -19.125  34.875               NaN
                      

[42]
[18]
The file opened successfully
convert lat and lon
[array([-19.625, -19.375, -19.125])]
[array([34.375, 34.625, 34.875])]
[-19.625 -19.375 -19.125]
Empty df
df
                                                                  pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2099 -19.625  34.375               NaN
                                    02-01-2099 -19.625  34.375               NaN
                                    03-01-2099 -19.625  34.375               NaN
                                    04-01-2099 -19.625  34.375               NaN
                                    05-01-2099 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2099 -19.125  34.875               NaN
                                    28-12-2099 -19.125  34.875               NaN
                      

In [34]:
df_climate_var

pr mm_per_year
Name project  Experiment Model      Date       Latitude Longitude               
WTP_Mutua_EIB ssp245     ACCESS-CM2 01-01-2015 -19.625  34.375               NaN
                                    02-01-2015 -19.625  34.375               NaN
                                    03-01-2015 -19.625  34.375               NaN
                                    04-01-2015 -19.625  34.375               NaN
                                    05-01-2015 -19.625  34.375               NaN
...                                                                          ...
                                    27-12-2100 -19.125  34.875               NaN
                                    28-12-2100 -19.125  34.875               NaN
                                    29-12-2100 -19.125  34.875               NaN
                                    30-12-2100 -19.125  34.875               NaN
                                    31-12-2100 -19.125  34.875               NaN

[94233 rows x 1 columns]

In [35]:
path = os.path.join(out_path, 'pr_day_ACCESS-CM2_ssp245_r1i1p1f1_gn_2018.nc')
ds= xr.open_dataset(path)
ds

<xarray.Dataset>
Dimensions:  (time: 365, lat: 81, lon: 61)
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01T12:00:00 ... 2018-12-31T12:00:00
  * lat      (lat) float64 -29.88 -29.62 -29.38 -29.12 ... -10.38 -10.12 -9.875
  * lon      (lon) float64 30.12 30.38 30.62 30.88 ... 44.38 44.62 44.88 45.12
Data variables:
    pr       (time, lat, lon) float32 ...
Attributes: (12/27)
    activity:              NEX-GDDP-CMIP6
    contact:               Dr. Rama Nemani: rama.nemani@nasa.gov, Dr. Bridget...
    Conventions:           CF-1.7
    creation_date:         2021-10-04T14:02:33.358203+00:00
    frequency:             day
    institution:           NASA Earth Exchange, NASA Ames Research Center, Mo...
    ...                    ...
    cmip6_license:         CC-BY-SA 4.0
    History:               Translated to CF-1.0 Conventions by Netcdf-Java CD...
    geospatial_lat_min:    -29.875
    geospatial_lat_max:    -9.875
    geospatial_lon_min:    30.125
    geospatial_lon_max:    45.125

In [30]:
ds.pr.values

array([[[1.13846079e-04, 1.23151767e-04, 1.35496943e-04, ...,
                    nan,            nan,            nan],
        [1.44013160e-04, 1.56217066e-04, 1.72565109e-04, ...,
                    nan,            nan,            nan],
        [1.77284572e-04, 1.94649241e-04, 2.15101332e-04, ...,
                    nan,            nan,            nan],
        ...,
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
                    nan,            nan,            nan],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
                    nan,            nan,            nan],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
                    nan,            nan,            nan]],

       [[1.28340500e-04, 1.02697370e-04, 8.02535433e-05, ...,
                    nan,            nan,            nan],
        [1.15504299e-04, 9.61985352e-05, 8.02201030e-05, ...,
                    nan,            nan,            nan],
        [1.02312770e-04, 

In [39]:
#df.loc[(name_project[p],SSP,model_simulation,time,lat_of_interest[p][k],lon_of_interest[p][k]),(name_variable+' '+unit,)] = 
len(ds.variables['pr'].isel(lat=42,lon=18).values)

365

In [ ]:
# Register information

# register dataframe in a csv format
title_file = 'All_projects_moz_'+name_project[project]+'_'+variable_of_interest+'_'+unit+'_'+str(start_year)+'-'+str(stop_year)+'several_lat_lon_sansSSP370.csv'
path_for_csv = os.path.join(out_path,'csv_file',variable_of_interest+'_'+unit+'_'+time_aggregations[0]+'_'+str(start_year)+'-'+str(stop_year))
path_csv = df_to_csv(df_climate_var,path_for_csv,title_file)

# register path_file_not_found in a file format
if path_file_not_found != []:
    txt_file_path = os.path.join(path_for_csv,'Path_file_not_found')
    with open(txt_file_path, 'w') as text_file:
        text_file.write(path_file_not_found)
    print('Not every files were found')
else:
    print('Every files were found')
        
# register ds_did_not_open in a file format
if ds_did_not_open != []:
    txt_file_path = os.path.join(path_for_csv,'ds_did_not_open')
    with open(txt_file_path, 'w') as text_file:
        text_file.write(ds_did_not_open)
    print('Not every files were opened successfully')
else:
    print('Every files were opened')